# Generated by Django 6.0.3 on 2026-03-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
