# Generated by Django 6.0.3 on 2026-03-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
