# Generated by Django 6.0.3 on 2026-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_payment_transferrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='reason',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=20),
        ),
    ]
