# Generated by Django 6.0.3 on 2026-07-09 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_stockledger_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='product',
            name='trade_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('EXECUTIVE', 'Executive'), ('MANAGER', 'Store Manager'), ('SUPER_ADMIN', 'Super_Admin'), ('PROCUREMENT', 'Procurement'), ('FINANCE', 'Finance'), ('STORE_USER', 'Store_User')], default='MANAGER', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseheader',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('PART_RECEIVED', 'Part Received'), ('RECEIVED', 'Received'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsolidatedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RFQ', 'RFQ'), ('PO_CREATED', 'PO Created'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidatedOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.consolidatedorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.product')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.purchaseheader')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_received', models.DecimalField(decimal_places=4, max_digits=14)),
                ('batch_no', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.goodsreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('trade_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_no', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('CONSOLIDATED', 'Consolidated'), ('ORDERED', 'Ordered'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.DecimalField(decimal_places=4, max_digits=14)),
                ('qty_approved', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=100)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consolidatedorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierQuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.supplierquotation')),
            ],
        ),
    ]
