# Generated by Django 6.0.3 on 2026-07-10 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_product_reorder_level_product_reorder_qty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsreceipt',
            old_name='received_date',
            new_name='received_at',
        ),
        migrations.RenameField(
            model_name='goodsreceiptline',
            old_name='qty_received',
            new_name='received_qty',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='grn_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('RECEIVED', 'Received'), ('VERIFIED', 'Verified')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='ordered_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='accounts.purchaseheader'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_no',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('SENT_FINANCE', 'Sent Finance'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.goodsreceipt')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.purchaseheader')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('trade_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.supplierinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank'), ('MPESA', 'Mpesa'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], max_length=20)),
                ('reference', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.supplierinvoice')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
