# Generated by Django 6.0.3 on 2026-07-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_received_date_goodsreceipt_received_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='required_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
