# Generated by Django 6.0.3 on 2026-07-13 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_requisition_required_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consolidatedorderline',
            old_name='order',
            new_name='consolidated_order',
        ),
        migrations.RenameField(
            model_name='consolidatedorderline',
            old_name='qty',
            new_name='total_qty',
        ),
        migrations.AlterField(
            model_name='consolidatedorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('CONSOLIDATED', 'Consolidated'), ('ORDERED', 'Ordered'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='consolidatedorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.supplier'),
        ),
    ]
