# Generated by Django 6.0.3 on 2026-07-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_order_consolidatedorderline_consolidated_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionline',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='consolidated',
            field=models.BooleanField(default=False),
        ),
    ]
