# Generated by Django 6.0.3 on 2026-07-13 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_consolidatedorder_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierquotation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='quotation_no',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='supplierquotationline',
            name='quoted_cost',
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='awarded_supplier_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='consolidated_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='accounts.consolidatedorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='created_supplier_quotations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='rfq_no',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierquotationline',
            name='awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierquotationline',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=10, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierquotationline',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='supplierquotationline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('AWARDED', 'Awarded')], default='DRAFT', max_length=20),
        ),
    ]
