# Generated by Django 6.0.3 on 2026-07-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_supplierquotation_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedorder',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.branch'),
            preserve_default=False,
        ),
    ]
