# Generated by Django 6.0.3 on 2026-07-20 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_supplierinvoiceline_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidatedorder',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.branch'),
        ),
        migrations.CreateModel(
            name='ConsolidatedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fulfilled_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consolidated_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounts.consolidatedorderline')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.requisition')),
                ('requisition_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.requisitionline')),
            ],
        ),
    ]
