# Generated by Django 6.0.3 on 2026-07-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_consolidatedorder_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidatedorder',
            name='branch',
        ),
        migrations.AddField(
            model_name='consolidatedorderline',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.branch'),
        ),
    ]
