# Generated by Django 6.0.3 on 2026-07-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_insurance_salesheader_auth_no_salesheader_member_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancescheme',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
