# Generated by Django 6.0.3 on 2026-07-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_insurancescheme_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesheader',
            name='member_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
