# Generated by Django 6.0.3 on 2026-07-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_salesheader_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name="salesheader",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("MPESA", "M-Pesa"),
                    ("INSURANCE", "Insurance"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
    ]
