# Generated by Django 6.0.3 on 2026-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_product_cash_markup_max_product_cash_markup_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesline',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
