# Generated by Django 6.0.3 on 2026-07-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_salesline_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_margin_pct',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
