# Generated by Django 6.0.3 on 2026-08-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_product_max_margin_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='po_line',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.purchaseline'),
            preserve_default=False,
        ),
    ]
