# Generated by Django 6.0.3 on 2026-09-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_goodsreceiptline_po_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesheader',
            name='mpesa_mode',
            field=models.CharField(blank=True, choices=[('STK', 'STK Push'), ('MANUAL', 'Manual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('INSURANCE', 'Insurance'), ('CARD', 'Card')], default='CASH', max_length=20),
        ),
    ]
