# Generated by Django 6.0.3 on 2026-09-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_salesheader_mpesa_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledger',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
