# Generated by Django 6.0.3 on 2026-09-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_stockledger_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='receipt_mode',
            field=models.CharField(choices=[('ORIGINAL_BRANCHES', 'Allocate to original requisition branches'), ('CONSOLIDATED_BRANCH', 'Receive at one selected branch')], default='CONSOLIDATED_BRANCH', max_length=30),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='invoiced_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='consolidated_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='accounts.consolidatedorderline'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='receipt_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='accounts.goodsreceiptline'),
        ),
        migrations.AddField(
            model_name='transferrequestline',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='accounts.consolidatedallocation'),
        ),
        migrations.AlterField(
            model_name='consolidatedallocation',
            name='allocated_qty',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='consolidatedallocation',
            name='fulfilled_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='GoodsReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='accounts.consolidatedallocation')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch')),
                ('receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounts.goodsreceiptline')),
            ],
        ),
    ]
