# Generated by Django 6.0.3 on 2026-09-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_goodsreceipt_receipt_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedallocation',
            name='transferred_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='supplierquotationline',
            name='consolidated_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='accounts.consolidatedorderline'),
        ),
        migrations.AlterField(
            model_name='consolidatedorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('CONSOLIDATED', 'Consolidated'), ('RFQ', 'Request for Quote'), ('AWARDED', 'Awarded'), ('ORDERED', 'Ordered'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferrequestline',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
