# Generated by Django 6.0.3 on 2026-09-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_consolidatedallocation_transferred_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseheader',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='buying_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
