# Generated by Django 6.0.3 on 2026-09-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_purchaseheader_is_urgent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCentralSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('SALE', 'Sale'), ('GRN', 'Goods receipt'), ('PAYMENT', 'Payment')], max_length=20)),
                ('entity_id', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='accounts_bu_entity__b41e2e_idx'), models.Index(fields=['status', 'created_at'], name='accounts_bu_status_05f465_idx')],
            },
        ),
    ]
