# Generated by Django 6.0.3 on 2026-03-17 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('as_of', models.DateTimeField()),
                ('features', models.JSONField(default=dict)),
                ('label', models.FloatField(blank=True, null=True)),
                ('split', models.CharField(default='train', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('params', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('status', models.CharField(default='running', max_length=32)),
                ('model_name', models.CharField(default='prophet', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('yhat', models.FloatField()),
                ('yhat_lower', models.FloatField()),
                ('yhat_upper', models.FloatField()),
                ('model_version', models.CharField(default='seasonal-naive-v1', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
            options={
                'unique_together': {('date', 'branch', 'product', 'model_version')},
            },
        ),
    ]
